spring:
  profiles:
    default: dev

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: ehdgoanfrhkqorentksdlakfmrhekfgehfhrgksmsladlqhdngktkdnflskfkakstp

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: wlfkswlry
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

# h2 database web으로 확인
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.security.entity

server:
  port: 8080

redis:
  host: 127.0.0.1
  port: 6379

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/jwtauth?serverTimezone=Asia/Seoul
    username: kslee
    password: 9156
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # 절대 변경 x
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

#redis:
#  host: 172.17.0.2
#  port: 6379